### ISSUE TITLE
Unable to install plugin lib, says file not found

### ISSUE THREAD

**Issue by FumoVite** [catsout/wallpaper-engine-kde-plugin#235]
I am unable to install plugin lib. It says a certain .so file is not found. That file just doesn't exist anywhere in the directory, or on the entire computer.

" Install the project...
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:62 (file):
  file INSTALL cannot find "/home/simonf/Documents/KDE Wallpaper Engine
  Plugin/wallpaper-engine-kde-plugin/build/src/libWallpaperEngineKde.so": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

make: *** [Makefile:100: install] Error 1 "

Kde: 5.25.24
Qt: 5.15.5
OS: KDE neon 5.25
Installation Source: git and KDE Store, both "install" (only images and video with sound)

![image](https://user-images.githubusercontent.com/112498835/189540175-569e4563-02e4-47da-90b2-0404047b3bbb.png)
![image](https://user-images.githubusercontent.com/112498835/189540200-e8b461d9-0b83-415b-82c4-e3af28f23b2a.png)

I have redone everything multiple times and tried on fresh installs, yet i always get the same error message. 
I looked through every issue that had *something* to do with plugin lib, yet nothing helped. 
Literally anything would help at the moment, i have been trying to get it working for days.

**Comment by linsyking** [comment]
What are your whole steps to install this plugin?

**Comment by FumoVite** [comment]
I just follow the guide on the github page.
 "sudo apt install build-essential libvulkan-dev plasma-workspace-dev gstreamer1.0-libav \
liblz4-dev libmpv-dev python3-websockets qtbase5-private-dev \
libqt5x11extras5-dev \
qml-module-qtwebchannel qml-module-qtwebsockets"

git clone https://github.com/catsout/wallpaper-engine-kde-plugin.git
cd wallpaper-engine-kde-plugin

git submodule update --init

mkdir build && cd build
cmake .. -DUSE_PLASMAPKG=ON

make

make install_pkg

sudo make install

**Comment by linsyking** [comment]
can you post the output for `make`?

**Comment by FumoVite** [comment]
Just redid the installation process. Now i get a bunch of *i think* vulkan errors when using the 'make' command
https://pastebin.com/9NstXuB6

**Comment by catsout** [comment]
Fixed, please try new commit.

**Comment by FumoVite** [comment]
Everything works now, thank you very much.
When running make i still get some warnings, but the commands afterwards worked fine. 
https://pastebin.com/6LVBDrk9 if you want to take a look at them
